/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

-- 切换到chat2Data数据库  
USE chat2Data;

DROP TABLE IF EXISTS `tbl_user`;

CREATE TABLE `tbl_user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `userId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `nickname` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `email` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,
  `password` TEXT CHARACTER SET utf8mb4 NOT NULL,
  `status` TINYINT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `userId_i`
  ON `tbl_user` (`userId`);

CREATE UNIQUE INDEX `nickname_i`
  ON `tbl_user` (`nickname`);

CREATE UNIQUE INDEX `email_i`
  ON `tbl_user` (`email`);

