/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

-- 切换到chat2Data数据库  
USE chat2Data;

DROP TABLE IF EXISTS `tbl_session`;

CREATE TABLE `tbl_session` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `sessionId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `userId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `sessionId_i`
  ON `tbl_session` (`sessionId`);

