/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

-- 切换到chat2Data数据库  
USE chat2Data;

DROP TABLE IF EXISTS `tbl_fileInfo`;

CREATE TABLE `tbl_fileInfo` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `fileId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `fileName` VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL,
  `fileExt` VARCHAR(8) CHARACTER SET utf8mb4 NOT NULL,
  `fileSize` BIGINT UNSIGNED NOT NULL,
  `uploadTime` BIGINT UNSIGNED NOT NULL,
  `fdfsFileId` VARCHAR(64) CHARACTER SET utf8mb4 NULL,
  `userId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `chatSessionId` VARCHAR(32) CHARACTER SET utf8mb4 NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `fileId_i`
  ON `tbl_fileInfo` (`fileId`);

