/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

-- 切换到chat2Data数据库  
USE chat2Data;

DROP TABLE IF EXISTS `tbl_worksheet`;

CREATE TABLE `tbl_worksheet` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `fileId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `worksheetName` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `tableName` VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `fileId_i`
  ON `tbl_worksheet` (`fileId`);

ALTER TABLE `tbl_worksheet`
  ADD CONSTRAINT `tbl_worksheet_fileId_fk`
  FOREIGN KEY (`fileId`)
  REFERENCES `tbl_fileInfo` (`fileId`)
  ON DELETE CASCADE;