/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

-- 切换到chat2Data数据库  
USE chat2Data;

DROP TABLE IF EXISTS `tbl_chatSession`;

CREATE TABLE `tbl_chatSession` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `chatSessionId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `userId` VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
  `title` TEXT CHARACTER SET utf8mb4 NULL,
  `createTime` BIGINT UNSIGNED NOT NULL,
  `updateTime` BIGINT UNSIGNED NOT NULL,
  `messageCount` INT UNSIGNED NOT NULL,
  `modelName` TEXT CHARACTER SET utf8mb4 NOT NULL,
  `fileId` VARCHAR(32) CHARACTER SET utf8mb4 NULL,
  `sessionType` VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL,
  `dbConnectionInfo` TEXT CHARACTER SET utf8mb4 NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `chatSessionId_i`
  ON `tbl_chatSession` (`chatSessionId`);

ALTER TABLE `tbl_chatSession`
  ADD CONSTRAINT `tbl_chatSession_fileId_fk`
  FOREIGN KEY (`fileId`)
  REFERENCES `tbl_fileInfo` (`fileId`)
  ON DELETE CASCADE;