# Chat2Data 配置文件

# ETCD配置
--etcd_addr=http://dev-etcd:2379

# MySQL配置
--mysql_host=dev-msyql
--mysql_user=root
--mysql_passwd=123456
--mysql_db=chat2Data
--mysql_port=3306
--mysql_charset=utf8mb4

# Redis配置
--redis_host=dev-redis
--redis_port=6379
--redis_passwd=123456
--redis_db=0
--redis_pool_size=16

# FastDFS配置
--fdfs_trackers=dev-tracker:22122
--fdfs_connect_timeout=30
--fdfs_network_timeout=30

# 日志配置
--log_async=false
--log_level=2
--log_format=[%H:%M:%S][%-7l]: %v
--log_path=stdout

# 邮箱配置
--mail_username=ailiangshilove@163.com
--mail_password=SXdW58976zvQfWJk
--mail_url=smtps://smtp.163.com:465
--mail_from=ailiangshilove@163.com

# AI配置
--temperature=0.7
--max_tokens=2048
# Ollama配置参数
--ollama_model_name=llama2-7b-chatllama
--ollama_model_desc=llama模型描述
--ollama_endpoint=http://ollama:11434

# 子服务名称配置
--user_service=UserService
--file_service=FileService
--db_service=DatabaseService
--ai_service=AIService
--notify_service=NotifyService
--excel_service=ExcelParserService

# 服务注册：每个子服务器需要单独配置
--listen_port=${LISTEN_PORT}
--service_name=${SVC_SERVICE_NAME}
--service_addr=${SVC_SERVICE_ADDR}
