syntax = "proto3";
package chat2Data.AiService;
option cc_generic_services = true;

// 文件服务接口定义
//////////////////////// 获取模型列表 ////////////////////////
message GetModelsRequest {
    string request_id = 1;             // 请求ID
}

message ModelInfo {
    string name = 1;                  // 模型名称
    string desc = 2;                  // 模型描述
}

message GetModelsResult {
    repeated ModelInfo models = 1;    // 模型列表
}

message GetModelsResponse {
    string request_id = 1;             // 请求ID
    int32 error_code = 2;              // 错误码
    string error_msg = 3;              // 错误信息
    GetModelsResult result = 4;        // 模型列表         
}

//////////////////////// 新建聊天会话 ////////////////////////
message CreateChatSessionRequest {
    string request_id = 1;             // 请求ID
    string user_id = 2;                // 用户ID
    string model = 3;                  // 模型名称
    string session_type = 4;           // 会话类型：excel/database
    string db_connection_info = 5;     // 数据库连接信息JSON
}
// db_connection_info：该字段在数据库场景下使用，当用户点击聊天会话时，如果该聊天会话是database场景，该字段内部为数据库连接信息

message CreateChatSessionData {
    string chat_session_id = 1;        // 聊天会话Id
    string model = 2;                  // 模型名称
}

message CreateChatSessionResult {
    CreateChatSessionData session = 1; // 聊天会话数据
}

message CreateChatSessionResponse {
    string request_id = 1;             // 请求ID
    int32 error_code = 2;              // 错误码
    string error_msg = 3;              // 错误信息
    CreateChatSessionResult result = 4; // 聊天会话数据
}

//////////////////////// 获取聊天会话列表 ////////////////////////
message GetSessionsRequest {
    string request_id = 1;             // 请求ID
    string user_id = 2;                // 用户ID
}

message SessionInfo {
    string id = 1;                 // 会话Id
    string model = 2;              // 模型名称
    string title = 3;              // 会话标题
    int64 created_at = 4;          // 创建时间
    int64 updated_at = 5;          // 最近活跃时间
    int32 message_count = 6;       // 消息数量
    string first_user_message_content = 7; // 首条消息内容(不超过20字)
    string session_type = 8;       // 会话类型：excel/database
    string db_connection_info = 9; // 数据库连接信息JSON（数据库场景）
}

message GetSessionsResult {
    repeated SessionInfo sessionInfo = 1;     // 会话列表
}

message GetSessionsResponse {
    string request_id = 1;             // 请求ID
    int32 error_code = 2;              // 错误码
    string error_msg = 3;              // 错误信息
    GetSessionsResult result = 4;      // 会话列表
}

//////////////////////// 获取指定会话的历史消息 ////////////////////////
message GetSessionHistoryRequest {
    string request_id = 1;        // 请求ID
    string user_id = 2;           // 用户ID---用来检测当前获取的聊天会话确实属于该用户所有
    string chat_session_id = 3;   // 聊天会话Id
}

message HistoryMessage {
    string id = 1;                 // 消息Id
    string role = 2;               // "user" or "assistant" user表示用户消息，assistant表示AI消息
    string content = 3;            // 消息内容
    int64 timestamp = 4;           // 消息时间戳
}

message GetSessionHistoryResult {
    string file_id = 1;               // 可选，仅在会话关联了文件时存在
    string session_type = 2;          // 会话类型：excel/database
    string db_connection_info = 3;    // 数据库连接信息JSON（数据库场景）
    repeated HistoryMessage messages = 4; // 历史消息列表
}

message GetSessionHistoryResponse {
    string request_id = 1;            // 请求ID
    int32 error_code = 2;             // 错误码
    string error_msg = 3;             // 错误信息
    GetSessionHistoryResult result = 4; // 历史消息列表
}
/*
 * 当用户点击某个历史消息项时，如果该历史消息项是Excel场景，则跳转到Excel页面，通过file_id预览Excel文件，在Excel页面上展示Excel文件的内容
 * 如果该历史消息项是数据库场景，则跳转到数据库页面，通过db_connection_info新建数据库连接，在数据库页面上展示数据库的内容
 */

//////////////////////// 删除指定会话 ////////////////////////
message DeleteSessionRequest {
    string request_id = 1;             // 请求ID
    string user_id = 2;                // 用户ID
    string chat_session_id = 3;        // 聊天会话ID
}

message DeleteSessionResponse {
    string request_id = 1;             // 请求ID
    int32 error_code = 2;              // 错误码
    string error_msg = 3;              // 错误信息
}

//////////////////////// 发送消息(流式响应) ////////////////////////
enum DataType {
  EXCEL = 0; // Excel场景
  MYSQL = 1; // MySQL场景
  SQLITE = 2; // SQLite场景
}

message SendMessageRequest {
    string request_id = 1;          // 请求ID
    string session_id = 2;          // 会话ID
    string user_id = 3;             // 用户ID
    string chat_session_id = 4;     // AI聊天会话ID
    string chat_type = 5;           // 聊天类型：excel/database/plain
    string message = 6;             // 用户消息内容
    string file_id = 7;             // 文件ID(Excel场景)
    DataType db_type = 8;           // 数据类型(数据库场景)
    string db_connect_id = 9;       // 数据库连接ID(数据库场景)
    string table_name = 10;          // 表名, 多个表名之间由逗号分隔(数据库场景)
}
/*
 * session_type: 会话类型：excel或database/plain
 * - excel: Excel场景, file_id字段不为空
 * - database: 数据库场景, db_connect_id字段不为空，db_type字段代表了具体的数据库类型, table_name字段表示要操作的数据库表
 * - plain: 普通场景
 */

message SendMessageResult {
    bool done = 1;                     // 是否完成
    string content = 2;                // 消息片段
}

message SendMessageResponse {
    string request_id = 1;             // 请求ID
    int32 error_code = 2;              // 错误码
    string error_msg = 3;              // 错误描述符
    SendMessageResult result = 4;      // 消息结果
}

//////////////////////// 更新会话文件关联 ////////////////////////
message UpdateSessionFileRequest {
    string request_id = 1;               // 请求ID
    string user_id = 2;                  // 用户ID
    string chat_session_id = 3;          // 聊天会话ID
    string file_id = 4;                  // 文件ID
}

message UpdateSessionFileResponse {
    string request_id = 1;               // 请求ID
    int32 error_code = 2;                // 错误码
    string error_msg = 3;                // 错误描述符
}

//////////////////////// AI模型服务RPC定义 ////////////////////////
service AIService {
    // 获取支持模型
    rpc GetModels(GetModelsRequest) returns (GetModelsResponse);
    // 创建新会话
    rpc CreateSession(CreateChatSessionRequest) returns (CreateChatSessionResponse);
    // 获取会话列表
    rpc GetSessions(GetSessionsRequest) returns (GetSessionsResponse);
    // 获取指定会话的历史消息
    rpc GetSessionHistory(GetSessionHistoryRequest) returns (GetSessionHistoryResponse);
    // 删除会话
    rpc DeleteSession(DeleteSessionRequest) returns (DeleteSessionResponse);
    // 更新会话文件关联
    rpc UpdateSessionFile(UpdateSessionFileRequest) returns (UpdateSessionFileResponse);
    // 发送消息(流式响应)
    rpc SendMessage(SendMessageRequest) returns (stream SendMessageResponse);
}