syntax = "proto3";
package chat2Data.notifyService;
option cc_generic_services = true;

// 通知服务接口定义
//////////////////////// 发送验证码 ////////////////////////
message SendVerifyCodeRequest {
  string request_id = 1;    // 请求ID
  string email = 2;         // 收件人邮箱
  string code = 3;          // 验证码
}

message SendVerifyCodeResponse {
  string request_id = 1;    // 请求ID
  int32 error_code = 2;     // 错误码
  string error_msg = 3;     // 错误描述符
}

//////////////////////// 发送邮件 (普通邮件) ////////////////////////
message SendEmailRequest {
  string request_id = 1;    // 请求ID
  string to_email = 2;      // 收件人邮箱
  string subject = 3;       // 邮件主题
  string content = 4;       // 邮件内容（HTML格式）
}

message SendEmailResponse {
  string request_id = 1;    // 请求ID
  int32 error_code = 2;     // 错误码
  string error_msg = 3;     // 错误描述符
}

// 通知服务RPC定义
service NotifyService {
  // 发送验证码邮件
  rpc SendVerifyCode(SendVerifyCodeRequest) returns (SendVerifyCodeResponse);
  // 发送普通本邮件
  rpc SendEmail(SendEmailRequest) returns (SendEmailResponse);
}